name: update calendar

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
      - name: update calender
        env:
          TIMETREE_ACCESS_TOKEN: ${{secrets.TIMETREE_ACCESS_TOKEN}}
          TIMETREE_CALENDAR_ID: ${{secrets.TIMETREE_CALENDAR_ID}}
        run: |
          python main.py
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Update calender"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
